kind: ServiceAccount
apiVersion: v1
metadata:
  name: "jhub-singleuser"
  annotations: 
    iam.gke.io/gcp-service-account: jhub-singleuser-serviceaccount@corn-field-397603.iam.gserviceaccount.com
automountServiceAccountToken: true